steps:
  - name: 'gcr.io/cloud-builders/docker'
    dir: monolith
    args: [ 'build', '-t', 'us-central1-docker.pkg.dev/haroonc-test/private-test/monolith-webapp:latest', '.' ]  
options:
  requestedVerifyOption: VERIFIED

images: ['us-central1-docker.pkg.dev/haroonc-test/private-test/monolith-webapp:latest']
